apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: enterprise-ms
data:
  USER_SERVICE_PORT: "8081"
  USER_SERVICE_DB_HOST: "app-db"
  USER_SERVICE_DB_PORT: "5432"
  USER_SERVICE_DB_USER: "postgres"
  USER_SERVICE_DB_NAME: "appdb"
  USER_SERVICE_LOG_LEVEL: "info"
  USER_SERVICE_RATE_LIMIT: "100"

  ORDER_SERVICE_PORT: "8082"
  ORDER_SERVICE_DB_HOST: "app-db"
  ORDER_SERVICE_DB_PORT: "5432"
  ORDER_SERVICE_DB_USER: "postgres"
  ORDER_SERVICE_DB_NAME: "appdb"
  ORDER_SERVICE_LOG_LEVEL: "info"
  ORDER_SERVICE_RATE_LIMIT: "100"
  ORDER_SERVICE_USER_SERVICE_URL: "http://user-service:8081"
  CIRCUIT_BREAKER_MAX_REQUESTS: "3"
  CIRCUIT_BREAKER_INTERVAL: "60"
  CIRCUIT_BREAKER_TIMEOUT: "30"

  REPOSITORY_SERVICE_PORT: "8083"
  REPOSITORY_SERVICE_DB_HOST: "app-db"
  REPOSITORY_SERVICE_DB_PORT: "5432"
  REPOSITORY_SERVICE_DB_USER: "postgres"
  REPOSITORY_SERVICE_DB_NAME: "appdb"
  REPOSITORY_SERVICE_LOG_LEVEL: "info"
  REPOSITORY_SERVICE_RATE_LIMIT: "100"

  AUTH_JWT_ISSUER: "enterprise-microservice-system"
  AUTH_JWT_AUDIENCE: "enterprise-microservice-system"
  AUTH_TOKEN_TTL_MINUTES: "60"
  AUTH_CLIENT_ID: "admin"
  AUTH_CLIENT_ROLES: "admin"
  AUTH_SERVICE_SUBJECT: "order-service"
  AUTH_SERVICE_ROLES: "service"

  REDIS_ENABLED: "true"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_TTL_SECONDS: "300"
