apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-ms
  namespace: enterprise-ms
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  rules:
    - host: enterprise.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-portal
                port:
                  number: 80
