apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: enterprise-ms
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
  AUTH_JWT_SECRET: "change-me"
  AUTH_CLIENT_SECRET: "admin123"
  REDIS_PASSWORD: ""
